### ISSUE TITLE
Feature Request: Ability to count whitespace

### ISSUE THREAD

**Issue by Will-at-FreedomDev** [chemodax/WordCount#3]
I also posted this question on the marketplace, but I also wanted to post here for visibility.

> I noticed that this extension does not actually count whitespace. Is there some way to configure the extension to include whitespace (such as spaces) in the character count? I looked for this extension specifically for the ability to count spaces. FYI I am hardcoding a "spacer" of fixed length and wanted to quickly know if I put the exact correct number of spaces, but unfortunately the extension shows "0" chars. Thanks!

![image](https://github.com/chemodax/WordCount/assets/59396813/df476696-9375-4b15-97f2-d2a972fc14d1)

**Comment by chemodax** [comment]
Well that is my fault.

Originally this was extension to count words, then I added ability to count characters, but made it in winword style.

I think it makes more sense to count whitespace as character like Sublime Text does.

It's easy to change. The only problem that it will be behavior change. 

What do you think?

**Comment by willherr** [comment]
> Well that is my fault.
> 
> Originally this was extension to count words, then I added ability to count characters, but made it in winword style.
> 
> I think it makes more sense to count whitespace as character like Sublime Text does.
> 
> It's easy to change. The only problem that it will be behavior change. 
> 
> What do you think?

Strictly speaking, whitespace characters are still characters. So I believe that it is intuitive for them to be counted ☺️ I think the behavior change is necessary imo

**Comment by chemodax** [comment]
Fixed in [90261d5](https://github.com/chemodax/WordCount/commit/90261d5055ad0d048c8efc0ce8130b1d4adfa88b). Fix available in 0.6.0.
